server:
  port: 8000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://112.74.41.177:5432/legal
    username: postgres
    password: 123456

swagger:
  enabled: true

logging:
  level:
    root: Info

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
