server:
  port: 8000
servlet:
  context-path: "/DwWebApi"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://112.74.41.177:5432/legal
    username: postgres
    password: "!QAZ2wsx#EDC"
swagger:
  enabled: true

logging:
  level:
    root: Info

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
