server:
  port: 8000
servlet:
  context-path: "/DwWebApi"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://68.109.202.164:5432/legal
    username: postgres
    password: Xfz-1017
swagger:
  enabled: true

logging:
  level:
    root: Info

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
