server:
  port: 8002
#servlet:
#  context-path: "/fsga/dw3"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://112.74.41.177/legal
    username: postgres
    password: "!QAZ2wsx#EDC"
#    url: jdbc:postgresql://68.109.202.164:5432/legal
#    username: postgres
#    password: Xfz-1017
swagger:
  enabled: true

logging:
  level:
    root: Info

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
multipart:
  maxRequestSize: 2000MB
  maxFileSize: 2000MB


