server:
  port: 8087

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://112.74.41.177/legal
    username: postgres
    password: !QAZ2wsx#EDC

swagger:
  enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
