server:
  port: 8087
  servlet:
   context-path: "/fsga/dw2"


#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://68.109.202.164:5432/legal
#    username: postgres
#    password: "Xfz-1017"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://112.74.41.177:5432/legal
    username: postgres
    password: "!QAZ2wsx#EDC"
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

swagger:
  enabled: true

logging:
  level:
    root: info

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
