server:
  port: 8088

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://112.74.41.177/legal
    username: postgres
    password: 123456

swagger:
  enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
