server:
  port: 10086

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.10.88:5432/legal
    username: postgres
    password: 123456

swagger:
  enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml