server:
  port: 8089

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Bail
    username: postgres
    password: 1234

swagger:
  enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
