spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://112.74.41.177:5432/legal
    username: postgres
    password: 123456
    initial-size: 2
    min-idle: 1
    max-active: 10
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-edle-time-millis: 300000
    filters: stat

swagger:
  enabled: true

logging:
  level:
    root: info

mybatis:
  mapper-locations: classpath:mapper/**/*.xml